### ノート　Python_11_NumPyの使い方

In [1]:
import numpy as np  #インポートする
a = np.array([0,1,2])
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[0 1 2]
int32


In [ ]:
import numpy as np  #インポートする
a = np.random.rand(5,2)
print(type(a))
print(a)
print(a.dtype)

<class 'numpy.ndarray'>
[[0.34577926 0.40526682]
 [0.59357197 0.62685779]
 [0.17570616 0.40188758]
 [0.66915977 0.86376417]
 [0.93595257 0.08193663]]
float64


In [ ]:
import numpy as np  #numpyインポートする

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.arange(1,10)
print(a)
print(b)

c = b.copy()
c = np.append(c,0).reshape()
print(c)



[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5]
 [6 7 8 9 0]]


In [ ]:
# 練習問題　コード１
import numpy as np 

a = np.array([1,2,3,4,5,6,7,8,9])
b = np.arange(1,10)
b=b.reshape(9,1)
print(a)
print(b)
c = a * b
print(c)

[1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]


In [ ]:
# 練習問題　コード2
import numpy as np
d = np.zeros((9,9))
d = d.astype(np.int8)  #astype完全に忘れてる・・　（int8ならメモリ使用量が減る
#print(d)
#2重ループで九九の表
for i in range (9):
    for j in range (9):
        d[i,j] = (i+1) * (j+1)
print(d)


[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
